FROM golang:1.22.0-bookworm

WORKDIR /app

RUN apt-get -y update
RUN apt-get -y upgrade
RUN apt-get install -y ffmpeg
RUN go install github.com/cosmtrek/air@latest

RUN rm -rf /tmp
RUN mkdir -p /tmp

COPY go.mod go.sum ./
RUN go mod download

COPY . .

CMD air -c .air.toml
